name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache the dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build staging
        run: npm run build:staging -- --prod

      - name: Compress the html, css and js files in dist
        uses: charlesworth/compress-action@master
        with:
          target-directory: 'dist/expert-consultation-client'

      - name: Deploy to S3 staging
        if: github.ref == 'refs/heads/develop'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_TEST }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'dist/expert-consultation-client'

      - name: Build the Docker image
        if: github.ref == 'refs/heads/develop'
        run: |
          docker build . \
          --file etc/docker/Dockerfile-dev \
          --tag ${{ secrets.ORGANIZATION }}/${{ secrets.REPO }}:latest

      - name: Login to docker registry
        if: github.ref == 'refs/heads/develop'
        run: docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}

      - name: Push to docker registry
        if: github.ref == 'refs/heads/develop'
        run: docker push ${{ secrets.ORGANIZATION }}/${{ secrets.REPO }}:latest
